server_connect_timeout: 5000
enforce_secure_profile: false
forge_support: false
player_limit: -1
log_pings: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
timeout: 30000
log_commands: false
online_mode: false
disabled_commands:
- disabledcommandhere
servers:
  server1:
    motd: Welcome to Server1!
    address: server1:25566
    restricted: false
  server2:
    motd: Welcome to Server2!
    address: server2:25567
    restricted: false
  server3:
    motd: Welcome to Server3!
    address: server3:25568
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - server1
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_timeout: 5000
ip_forward: true
network_compression_threshold: 256
reject_transfers: false
remote_ping_cache: -1
connection_throttle: 4000
stats: 1ffc5914-9ec7-4270-bf4b-24cb45743187
connection_throttle_limit: 3
groups:
  md_5:
  - admin
prevent_proxy_connections: false
